[phases.setup]
commands = [
  "apt-get update && apt-get install -y python3-pip python3-dev build-essential libpq-dev python3.10-venv",
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install django",
  "/opt/venv/bin/pip install psycopg2",
  "/opt/venv/bin/pip install asgiref",
  "/opt/venv/bin/pip install sqlparse",
  "/opt/venv/bin/pip install packaging",
  "/opt/venv/bin/pip install typing_extensions",
  "/opt/venv/bin/pip install gunicorn"
]

[phases.start]
commands = [
  "/opt/venv/bin/gunicorn clinicaTendencias.wsgi:application --bind 0.0.0.0:$PORT"
]

