[phases.setup]
commands = [
  "apt-get update && apt-get install -y python3-pip python3-dev build-essential libpq-dev",
  "pip3 install django",
  "pip3 install psycopg2",
  "pip3 install gunicorn",
]

