[phases.setup]
commands = [
  "apt-get update && apt-get install -y python3-pip python3-dev build-essential libpq-dev",
  "pip3 install -r requirements.txt"
]

[phases.start]
commands = [
  "gunicorn clinicaTendencias.wsgi:application --bind 0.0.0.0:$PORT"
]