[phases.setup]
commands = [
  "apt-get update && apt-get install -y python3-pip python3-dev build-essential libpq-dev",
  "python3 -m venv venv",
  "source ./venv/bin/activate",
  "pip3 install django",
  "pip3 install psycopg2",
  "pip3 install gunicorn",
  "python3 manage.py runserver"
]

