# Generated by Django 5.1.1 on 2024-10-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('ct_pacienteId', models.AutoField(primary_key=True)),
                ('ct_pais', models.CharField(max_length=100)),
                ('ct_tipodocumentacion', models.CharField(max_length=50)),
                ('ct_primerapellido', models.CharField(max_length=100)),
                ('ct_segundoapellido', models.CharField(max_length=100)),
                ('ct_primernombre', models.CharField(max_length=100)),
                ('ct_segundonombre', models.CharField(blank=True, max_length=100)),
                ('ct_fechanacimiento', models.DateField()),
                ('ct_nombresexobiologico', models.CharField(max_length=50)),
                ('ct_nombreidentidadgenero', models.CharField(max_length=50)),
                ('ct_ocupacion', models.CharField(max_length=100)),
                ('ct_oposiciondonacion', models.CharField(max_length=50)),
                ('ct_fechaoposiciondonacion', models.DateField(blank=True, null=True)),
                ('ct_nombrevoluntadanticipada', models.CharField(blank=True, max_length=100)),
                ('ct_fechavoluntadanticipada', models.DateField(blank=True, null=True)),
                ('ct_categoriadiscapacidad', models.CharField(max_length=100)),
                ('ct_municipioresidencia', models.CharField(max_length=100)),
                ('ct_departamentoresidencia', models.CharField(max_length=100)),
                ('ct_comunidadetnica', models.CharField(max_length=100)),
                ('ct_pertenenciaetnica', models.CharField(max_length=100)),
                ('ct_nombrezonaterritorial', models.CharField(max_length=100)),
                ('ct_entidadresponsable', models.CharField(max_length=100)),
                ('ct_sexobiologicoid', models.CharField(default='01', max_length=2)),
                ('ct_identidadgeneroid', models.CharField(default='01', max_length=2)),
                ('ct_voluntadanticipadaprestadorid', models.CharField(default='01', max_length=2)),
                ('ct_zonaterritorialid', models.CharField(default='01', max_length=2)),
            ],
            options={
                'db_table': 'ct_paciente',
            },
        ),
    ]
