# Generated by Django 5.1.1 on 2024-10-26 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_paciente_ct_pacienteid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoIdentificacion',
            fields=[
                ('ct_documentoIdentificacionId', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('ct_nombreDocumentoIdentificacion', models.CharField(max_length=40)),
                ('ct_numeroDocumentoIdentificacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ct_documentoIdentificacion',
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ct_tipodocumentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.documentoidentificacion'),
        ),
    ]
